### ISSUE TITLE
Version `GLIBC_2.25' not found (required by ./loki-storage) on Ubuntu 16.04

### ISSUE THREAD

**Issue by ilie1988** [oxen-io/oxen-storage-server#394]
When running Loki-Storage on Ubuntu 16.04 it gives the error that GLIBC version is to old, on the daemon you can compile it by passing -DBACKCOMPAT=ON to cmake will make sure that the binary will run on systems having at least libc version 2.17.

SPECS:
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.7 LTS
Release:        16.04
Codename:       xenial

./loki-storage 0.0.0.0 8080
./loki-storage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by ./loki-storage)

**Comment by jagerman** [comment]
We don't officially support Ubuntu that old in our binaries (our static builds currently require 18.04).  That said, it *is* possible to compile things yourself, but it requires noticeable effort, including installing a modern C++ compiler (g++ 8+ or clang 8+).
