### ISSUE TITLE
Use non-deprecated tcp::resolver API

### ISSUE THREAD

**Issue by sachaaaaa** [oxen-io/oxen-storage-server#91]
(low priority)
We're currently using
```cpp
 tcp::resolver resolver(ioc);
 tcp::resolver::iterator destination =
        resolver.resolve(sn_address, "http", ec);
```
but the `resolve` overload that returns an `iterator` is marked deprecated.
We should use the one that returns `results_type` instead.

**Comment by jagerman** [comment]
No longer relevant.
