### ISSUE TITLE
Move utils implementation into cpp

### ISSUE THREAD

**Issue by sachaaaaa** [oxen-io/oxen-storage-server#99]

**Comment by sachaaaaa** [comment]
Not sure if this is still relevant.
The 3 functions in the header are templated, and would require the specializations to be explicitly declared if moved to a cpp, kinda beating the purpose of templates.

**Comment by msgmaxim** [comment]
This is very low priority, but I still want this. We should move implementation out of the header, so we don't recompile it every time we include `utils.h`.

If we write specialisations explicitly, we will still avoid code duplication which is the purpose of templates. The only thing we would give up is our code magically working for any type we don't know of (which is great if you are developing a generic library like `std::vector` which we don't in this case).

**Comment by aspieln3r** [comment]
I'd like to work on this. What exactly needs to be done?
moving out templates to a different file with multiple function declarations and place only function declaration on utils.hpp?

**Comment by jagerman** [comment]
This appears to have been done, for the most part; the only thing still inlined are some very simple inline functions added recently (which are quite useful to have in a header to allow the compiler to inline them, thus avoiding a function call), and some generic templated functions.
